language: emacs-lisp
dist: trusty
sudo: required

install:
  - curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/travis-eldev-and-evm > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use

env:
  - EVM_EMACS=emacs-26.1-travis
  - EVM_EMACS=emacs-26.2-travis
  - EVM_EMACS=emacs-26.3-travis

script:
  - git clone https://github.com/lordpretzel/advice-tools.git ~/scripts/elisp/advice-tools
  - git clone https://github.com/lordpretzel/xwidgets-reuse.git ~/scripts/elisp/xwidgets-reuse
  - sudo mkdir -p /usr/local/share/emacs/site-lisp/
  - sudo git clone https://github.com/djcb/mu.git /usr/local/share/emacs/site-lisp/
  - sudo chmod -R 666 /usr/local/share/emacs/site-lisp/mu/
  # - eldev -p -dtT test --expect 5
  # Also require that byte-compilation produces no warnings. --warnings-as-errors
  - eldev -dtT compile --set all
